name: 'cowjacket'
version: '1.0'
config-version: 2

profile: 'cowjacket'  # matches your profiles.yml

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  cowjacket:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table
